# Generated by Django 5.1.3 on 2024-12-07 20:36

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_reclamation_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='downtime',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('recovery_date'), '-', models.F('failure_date')), '/', models.Value(84600000000)), output_field=models.DecimalField(decimal_places=0, max_digits=1), verbose_name='Время простоя техники'),
        ),
    ]
