# Generated by Django 5.1.4 on 2024-12-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_reclamation_downtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbooks',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(max_length=128, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
