# Generated by Django 5.1.4 on 2024-12-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_handbooks_name_alter_machine_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='failure_desc',
            field=models.TextField(blank=True, verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='used_spares',
            field=models.TextField(blank=True, verbose_name='Используемые запчасти'),
        ),
    ]
